security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_login:
            pattern: /api/login
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: api_login
                username_path: 'email'
        api:
            pattern: ^/api/
            provider: app_user_provider
            stateless: true
            custom_authenticators:
                - App\Security\Authenticator\TokenAuthenticator
        main:
            lazy: true
            provider: app_user_provider
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
    role_hierarchy:
        ROLE_USER: [PUBLIC_ACCESS]
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
